import PDFDocument from 'pdfkit';
import { Lead } from '@prisma/client';

export function exportLeadsToPDFBuffer(leads: Lead[], companyName = 'PJN Technologies'): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header Banner
      doc.rect(0, 0, doc.page.width, 60).fill('#1E40AF');
      doc
        .fillColor('#FFFFFF')
        .fontSize(20)
        .font('Helvetica-Bold')
        .text('PJN LEADFLOW — LEAD DIRECTORY', 40, 20);

      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`Generated by ${companyName} | Total Leads: ${leads.length}`, 40, 42);

      doc.moveDown(3);

      let y = 80;

      leads.forEach((lead, index) => {
        if (y > 720) {
          doc.addPage();
          y = 40;
        }

        // Lead Container Box
        doc.roundedRect(40, y, 515, 80, 6).strokeColor('#E2E8F0').lineWidth(1).stroke();

        // Business Name & Category
        doc
          .fillColor('#1E293B')
          .fontSize(12)
          .font('Helvetica-Bold')
          .text(`${index + 1}. ${lead.businessName}`, 55, y + 10);

        doc
          .fillColor('#3B82F6')
          .fontSize(9)
          .font('Helvetica')
          .text(`Category: ${lead.category || 'General'} | City: ${lead.city || 'N/A'}`, 55, y + 26);

        // Rating & Details
        doc
          .fillColor('#64748B')
          .fontSize(9)
          .text(`Rating: ⭐ ${lead.rating || 0.0} (${lead.reviews || 0} reviews) | Status: ${lead.status}`, 55, y + 40);

        // Phone & WhatsApp Link
        const phoneStr = lead.phone ? `Phone: ${lead.phone}` : 'No Phone Available';
        doc
          .fillColor('#0F172A')
          .fontSize(10)
          .font('Helvetica-Bold')
          .text(phoneStr, 55, y + 56);

        if (lead.normalizedPhone) {
          const waUrl = `https://wa.me/${lead.normalizedPhone}`;
          doc
            .fillColor('#16A34A')
            .fontSize(10)
            .font('Helvetica-Bold')
            .text('🟢 Open WhatsApp Chat', 380, y + 56, { link: waUrl, underline: true });
        } else {
          doc.fillColor('#94A3B8').fontSize(9).font('Helvetica').text('No WhatsApp', 380, y + 56);
        }

        y += 92;
      });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
